# Site settings
title: RubyConfIndia
email: team@rubyconfindia.org
description: > # this means to ignore newlines until "baseurl:"
  The Indian edition of the international Ruby programming language conference.
  It is organized annually on a not-for-profit basis by volunteers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rubyconfindia.org" # the base hostname & protocol for your site
twitter_username: "@RubyConfIndia"
github_username: smtalimett
encoding: UTF-8
meta_title: RubyConfIndia - RubyConf's Indian edition
meta_description: > #
  The Indian edition of the international Ruby programming language conference.
  It is organized annually on a not-for-profit basis by volunteers.

# Build settings
markdown: kramdown
